name: Documentation

on:
  push:
    branches:
      - "*"

env:
  TEXMFHOME: ${{ github.workspace }}

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v2
        with:
          packages: |
            scheme-basic
            pgf
            pgfopts
            l3build
            fontspec
            microtype
            etoolbox
            titlesec
            footmisc
            bigfoot
            enumitem
            tocloft
            csquotes
            mathtools
            newtx
            xkeyval
            listings
            isodate
            substr
            cleveref
            biblatex
            biblatex-phys
            hypdoc
            txfonts
            biber

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache fonts
        id: font-cache
        uses: actions/cache@v2
        with:
          path: ~/.local/share/fonts
          key: fonts

      - name: Download Fira Code
        if: steps.font-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.local/share/fonts
          curl -LO https://github.com/tonsky/FiraCode/releases/download/6.2/Fira_Code_v6.2.zip
          unzip -j Fira_Code_v6.2.zip ttf/* -d ~/.local/share/fonts

      - name: Download EB Garamond
        if: steps.font-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.local/share/fonts
          curl -LO https://github.com/georgd/EB-Garamond/releases/download/nightly/EBGaramond.zip
          unzip -j EBGaramond.zip -d ~/.local/share/fonts

      - name: Update Lua font cache
        run: |
          fc-cache --force --verbose
          luaotfload-tool --update -vv

      - name: Build documentation
        run: |
          l3build doc

      - name: Upload PDF outputs
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs/tikz-feynman.pdf
