name: Labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml

jobs:
  sync-labels:
    name: Synchronise labels

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Synchronize labels
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yml
